<?php
require_once __DIR__.'/config.php'; require_once __DIR__.'/auth.php'; rts_require_login();
if(!rts_is_approver()){http_response_code(403);exit('Akses hanya untuk ADMIN atau ASS.');}
$message='';$error='';$isAdmin=rts_is_admin();
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_FILES['file_customer'])){
 $f=$_FILES['file_customer'];$replace=$isAdmin&&!empty($_POST['replace_all']);
 if($f['error']!==UPLOAD_ERR_OK)$error='File gagal diupload.';elseif($f['size']>10*1024*1024)$error='Ukuran file maksimal 10 MB.';else{$h=fopen($f['tmp_name'],'r');$header=fgetcsv($h);$header=array_map(fn($x)=>strtolower(trim((string)$x)),$header?:[]);$required=['id_customer','nama_toko','tipe_customer','salesman','alamat','kunjungan','hari','sales_district','longitude','latitude','status_aktif'];$missing=array_diff($required,$header);if($missing)$error='Kolom tidak lengkap: '.implode(', ',$missing);else{try{$conn->begin_transaction();if($replace&&!$conn->query('DELETE FROM master_toko'))throw new RuntimeException('Data lama gagal dihapus.');$insert=$conn->prepare('INSERT INTO master_toko (id_customer,nama_toko,tipe_customer,salesman,alamat,kunjungan,hari,sales_district,longitude,latitude,status_aktif) VALUES (?,?,?,?,?,?,?,?,?,?,?)');$update=$conn->prepare('UPDATE master_toko SET nama_toko=?,tipe_customer=?,salesman=?,alamat=?,kunjungan=?,hari=?,sales_district=?,longitude=?,latitude=?,status_aktif=? WHERE id_customer=?');$count=0;$skipped=0;while(($row=fgetcsv($h))!==false){if(count($row)===1&&trim($row[0])==='')continue;$d=array_pad($row,count($header),'');$v=array_combine($header,$d);$id=trim($v['id_customer']??'');if($id===''){ $skipped++;continue;}$type=strtoupper(trim($v['tipe_customer']??'REGULER'));if(!in_array($type,['REGULER','GSP'],true))$type='REGULER';$status=trim($v['status_aktif']??'')==='Nonaktif'?'Nonaktif':'Aktif';$check=$conn->prepare('SELECT id FROM master_toko WHERE id_customer=? LIMIT 1');$check->bind_param('s',$id);$check->execute();$exists=$check->get_result()->num_rows>0;if($exists){$update->bind_param('sssssssssss',$v['nama_toko'],$type,$v['salesman'],$v['alamat'],$v['kunjungan'],$v['hari'],$v['sales_district'],$v['longitude'],$v['latitude'],$status,$id);$ok=$update->execute();}else{$insert->bind_param('sssssssssss',$id,$v['nama_toko'],$type,$v['salesman'],$v['alamat'],$v['kunjungan'],$v['hari'],$v['sales_district'],$v['longitude'],$v['latitude'],$status);$ok=$insert->execute();}if(!$ok)throw new RuntimeException('Gagal pada ID Customer '.$id.': '.$conn->error);$count++;}$conn->commit();fclose($h);$message="$count data berhasil diproses".($skipped?", $skipped baris dilewati":"").'.';}catch(Throwable $e){$conn->rollback();$error='Upload dibatalkan: '.$e->getMessage();}}}}
}
require_once __DIR__.'/header.php';?><div class="card border-0 shadow-sm" style="max-width:900px"><div class="card-body p-4"><h3>Upload Data Customer</h3><p class="text-muted">ADMIN/ASS dapat upload CSV UTF-8.</p><?php if($message):?><div class="alert alert-success"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php endif;?><a class="btn btn-outline-success mb-3" href="template_customer.csv" download>Download Template CSV</a><form method="post" enctype="multipart/form-data"><input type="file" name="file_customer" class="form-control mb-3" accept=".csv,text/csv" required><?php if($isAdmin):?><div class="form-check border border-danger rounded p-3 mb-3"><input class="form-check-input" type="checkbox" name="replace_all" id="replaceAll"><label class="form-check-label text-danger fw-bold" for="replaceAll">Hapus semua data customer lama sebelum upload</label><div class="small text-muted">Gunakan hanya setelah backup. Data master_toko akan diganti seluruhnya.</div></div><?php endif;?><button class="btn btn-primary">Upload dan Update Data</button></form><hr><small class="text-muted">Jika ID Customer sudah ada, data diperbarui. Jika belum ada, data ditambahkan. Proses menggunakan transaksi dan akan dibatalkan jika terjadi error.</small></div></div><?php require_once __DIR__.'/footer.php';?>
